### ISSUE TITLE
Zip Download Security

### ISSUE THREAD

**Issue by ZoyaVariant** [opiter09/Fossil-Fighters-Champions-Randomizer#10]
Hi! Big fan! Huge FF enjoyer! Could you check on an issue with this repository? A security scan shows "Trojan:Script/Wacatac.B!ml" hidden within the files. I would really love to use this randomizer and I'm super excited to play the game in a new way but... you know...

P.S. I'm also looking at making a Fossil Fighters fangame and am actively recruiting. If you are interested, email me!
zoyavariant2442@gmail.com

**Comment by opiter09** [comment]
I'm sorry, I don't know what to tell you, Microsoft Defender isn't picking anything up for me. All the files in there look right, so I suppose you'll just have to trust me...

**Comment by ZoyaVariant** [comment]
I do trust ya! You have made great stuff in the past. I just wanted to mention something just in case! Thank you!
