### ISSUE TITLE
Treasure Lake: Todd vs Rupert oddity 

### ISSUE THREAD

**Issue by Willrocks147** [opiter09/Fossil-Fighters-Champions-Randomizer#2]
Essentially the tutorial teaching you types matter, the battle doesn't begin. Just a white screen.

**Comment by opiter09** [comment]
Would you be able to provide a save file from right before then?

**Comment by Willrocks147** [comment]
Saving before the battle? Yeah I can do that.

**Comment by opiter09** [comment]
What emulator do you use?

**Comment by Willrocks147** [comment]
Desmume

**Comment by opiter09** [comment]
Go to the folder where desmume is. you'll see a folder there named Battery. The save file is in there, called RomName.dsv

**Comment by Willrocks147** [comment]
Found it, but won't send in Github. 
[Save.zip](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/files/12744492/Save.zip)

Let me know if that worked?

**Comment by opiter09** [comment]
that worked

**Comment by opiter09** [comment]
thanks, this will make this much easier

**Comment by opiter09** [comment]
one more thing what randomizer settings did you use?

**Comment by Willrocks147** [comment]
Randomized fossils and teams. Otherwise kept it the same.

**Comment by opiter09** [comment]
Okay this should be fixed

**Comment by opiter09** [comment]
Let me know if there are problems

**Comment by Willrocks147** [comment]
Rupert fight started, it went through like normal, fight conceded and game has resumed! Thanks!
