### ISSUE TITLE
Todd Tournament. 

### ISSUE THREAD

**Issue by Willrocks147** [opiter09/Fossil-Fighters-Champions-Randomizer#3]
The first tourny fight is same white screen. Entering doors results in white screen then presumably crash. I am curious if the game got upset at the type tutorial was the same team for Todd, but for the tourny it was altered. 
[Save.zip](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/files/12749914/Save.zip)

**Comment by opiter09** [comment]
To be clear, this happened on a rom made with the newest randomizer?

**Comment by Willrocks147** [comment]
Yes

**Comment by opiter09** [comment]
Hey so the save you have white screens before I even get to the lobby, would you be able to just tell me the vanilla vivosaurs and person name of the team it stops working at?

**Comment by Willrocks147** [comment]
![image](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/assets/146299747/6f4a6a52-1595-41b6-bf71-37632f27b592)

**Comment by opiter09** [comment]
okay would you mind trying the new one? I cant guarantee it will work, but we should try the obvious change first, you know?

**Comment by Willrocks147** [comment]
Sure, I can give it a whirl.

**Comment by Willrocks147** [comment]
Hold up, wait a minute. I deleted all my files from the unpack. And I was able to get to the Todd fight! 
![image](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/assets/146299747/a3872d86-5da5-4ffa-b261-c99f01aa6e8b)

**Comment by opiter09** [comment]
There we go, problem solved

**Comment by Willrocks147** [comment]
Praise be, thanks for the help!
