### ISSUE TITLE
Crash when entering the Cranial Island Cleaning Room

### ISSUE THREAD

**Issue by WaterWitch** [opiter09/Fossil-Fighters-Champions-Randomizer#4]
Game seems to crash when entering the cleaning room of the second island. Occurred on 2 separate randomized roms, seems to be a consistent crash (occurs every time entering the room, not at random)

Using the DeSuMe emulator and randomized using default settings.

Save is attached, should be right in front of the door to the cleaning room.
[save.zip](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/files/12817662/save.zip)

**Comment by opiter09** [comment]
I have literally zero idea what is going on here. However, both Ribular and Illium cleaning do work, so for now I'd just recommend going there. If there is a moment where that becomes impossible, let me know and I'll try to knuckle down and figure it out.

**Comment by opiter09** [comment]
Never mind lol I just fixed it.

**Comment by WaterWitch** [comment]
Just confirmed on a new randomized rom that it works!
