### ISSUE TITLE
Crash when attempting to look at donation fossils

### ISSUE THREAD

**Issue by WaterWitch** [opiter09/Fossil-Fighters-Champions-Randomizer#5]
While trying out the new patch to confirm the fix mentioned in my last issue submission, got hit with a crash when I checked to see what donation fossils got randomized.

I've been able to look at the donation fossils in prior randomized roms, so I'm not sure if it's an issue with the new version or if the randomizer generated a result that the game is unhappy with.

save attached below, using the default randomizer settings
[savedonationcrash.zip](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/files/12829157/savedonationcrash.zip)

**Comment by opiter09** [comment]
Alas, Desmume won't even load your save for me. But I did check using a different save, the randomizer itself doesn't crash at the Donation Fossils.

**Comment by opiter09** [comment]
Would you mind sending your out.xdelta?

**Comment by WaterWitch** [comment]
Here you go
[outdelta.zip](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/files/12830891/outdelta.zip)

**Comment by WaterWitch** [comment]
I've tested it out with another randomized rom and it does not replicate the crash, I'll provide the save and out.xdelta for comparison with the one that does crash.

[savedonation-notcrash.zip](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/files/12835763/savedonation-notcrash.zip)
[outdelta-notcrash.zip](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/files/12835764/outdelta-notcrash.zip)

**Comment by opiter09** [comment]
I honestly have no clue what the problem is. Sorry.
