### ISSUE TITLE
Vivosaurs replacing single-fossil Vivosaurs (Curious & Possibly Giant) cannot be dug up beyond the Head Fossil

### ISSUE THREAD

**Issue by the-Lazarator** [opiter09/Fossil-Fighters-Champions-Randomizer#6]
I was using a spreadsheet to determine which Vivosaurs had replaced which in each area, and came to the conclusion that in Jungle Labyrinth, Futabi had replaced Anomalo and Tro had replaced Parapu (Anomalo and Parapu are each only found in one part of the map and the other Vivosaurs found alongside them I was able to find in other sections).

Problem: After way, way too many repeat visits, I could never find anything beyond their head fossils. Obviously enough to revive them and they wouldn't be locked out of moves in Champions but it does make leveling them up harder as well as completionism. 

My guess is since they are replacing Vivosaurs that are a single fossil piece, none of the rest of their bones can appear

I have NOT yet checked if this also applies to Giant fossil rocks or if getting more fossil chips will fix the issue

**Comment by opiter09** [comment]
Good catch. I had forgot I had done that that way, and mulling it over I have an idea to get you all the parts, since there do seem to be the fossil slots for it.

**Comment by opiter09** [comment]
The new version should resolve this. Although for Anomalo in JL specifically I still only get heads, but I checked and the fossils are there so that's out of my hands (especially since I couldn't find spawn percents for FFC).

**Comment by the-Lazarator** [comment]
Thank you for your speedy assistance!
