### ISSUE TITLE
Certain Random Fighters Crash Game

### ISSUE THREAD

**Issue by the-Lazarator** [opiter09/Fossil-Fighters-Champions-Randomizer#7]
I did not have this issue previously on this emulator playing the normal version of the game so it seems to be because of the randomizer

Sometimes when digging up a fossil rock, right at the point a fighter would pop out of the ground, the game will crash. It occurred with any Vivosaur, only head fossils I believe (granted I only had 2 possible parts to dig up), and does not occur every single time a random fighter appears. I am not sure if it's a certain fighter model causing the problem or a certain team (both fighter models and teams don't seem to be randomized so I have no clue what would cause this). This also occurred in Jungle Labyrinth, I did not have it happen in Treasure Lake but I didn't run into nearly as many fighters there

**Comment by opiter09** [comment]
Did you use the team level increaser? I've gotten similarly random crashes from that on FF1, since it still edits the files. I can't really explain what is going on though yet, or why it affects such a sporadic set of fighters.

**Comment by the-Lazarator** [comment]
I did, so I imagine that's the issue. A shame cause Champion's NPCs are woefully underlevelled

**Comment by opiter09** [comment]
the latest build should (emphasis on should) fix this. Let me know if it doesn't. I also experimentally turned back on teams randomization; if you try that, let me know how it goes.
