### ISSUE TITLE
Can't get randomized file

### ISSUE THREAD

**Issue by Nirgillo** [opiter09/Fossil-Fighters-Champions-Randomizer#8]
![ffcrrun](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/assets/146206354/cb4f5552-737b-453d-9284-94ba1c52deb3)

When I run the program, it ends up with this result without giving me the randomized ffc file. Is there something I am doing wrong?

**Comment by Nirgillo** [comment]
![randomerror](https://github.com/opiter09/Fossil-Fighters-Champions-Randomizer/assets/146206354/b119edfe-6d47-4654-bdbe-087f64a010e1)

Wanted to re-randomize but now every time I try to run the program it pops up with this text for a second then closes.

**Comment by opiter09** [comment]
I’m impressed you got a screenshot of it lol. But anyway you did drag the ROM onto the exe right? Not just double click it by itself?

**Comment by Nirgillo** [comment]
Ok thanks that was the problem. And lol I clipped it and screenshotted that frame.
